modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/chaoticunnatural/create-boards-and-boxes/issues"

[[mods]]
modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

#logoFile="examplemod.png"

authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"


[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.6,6.1.0)"
    ordering="NONE"
    side="BOTH"
